#!/usr/bin/python
"""
main ADaM application
"""

import sys
from PyQt4 import QtGui
from adamgui import AdamGui

if __name__ == "__main__":
    APP = QtGui.QApplication(sys.argv)
    AdamGui().show()
    sys.exit(APP.exec_())
