#!/usr/bin/python

import sys 
from PyQt4 import QtGui
from adamgui import AdamGui

if __name__ == "__main__":
    """
    main function for ADaM
    """  
    app = QtGui.QApplication(sys.argv) 
    AdamGui().show()
    sys.exit(app.exec_())
