#!/usr/bin/python

import sys 
from PyQt4 import QtGui, QtCore
from adamgui import AdamGui

if __name__ == "__main__":   
    app = QtGui.QApplication(sys.argv) 
    ui = AdamGui() 
    ui.show()
    
    sys.exit(app.exec_())